export const ENDPOINT = {
  AUTH: {
    signUp: "/api/auth/signup",
    teamMemberCreate: "/api/auth/team-member/create",
    allTeamMember: "/api/auth/team-member/all",
    signIn: "/api/auth/signin",
    signOut: "/api/auth/signout",
    forgoPassword: "/api/auth/forgot-password",
    updatePassword: "/api/auth/update-password",
    getUser: "/api/auth/profile",
  },
  PROJECT: {
    base: "/api/projects",
    byId: (id: string) => `/api/projects/${id}`,
    stats: "/api/projects/stats",
    byCustomer: (customerId: string) => `/api/projects/customer/${customerId}`,
    files: (projectId: string) => `/api/projects/${projectId}/files`,
    feedback: (projectId: string) => `/api/projects/${projectId}/feedback`,
    messages: (projectId: string) => `/api/projects/${projectId}/messages`,
  },
  TASK: {
    base: "/api/tasks",
    byId: (id: string) => `/api/tasks/${id}`,
    byProject: (projectId: string) => `/api/tasks/project/${projectId}`,
    byUser: (userId: string) => `/api/tasks/user/${userId}`,
    groups: "/api/tasks/groups",
    statusSummary: "/api/tasks/status/summary",
    batchAssign: (userId: string) => `/api/tasks/user/${userId}`,
  },
}
