// Simplify mock data to minimal structure
export const mockUser = {
  id: "user-1",
  email: "user@example.com",
  first_name: "Demo",
  last_name: "User",
  profile_image: null,
}

export const mockProfile = {
  id: "profile-1",
  user_id: "user-1",
  first_name: "Demo",
  last_name: "User",
  bio: "Demo user profile",
  avatar_url: null,
  created_at: new Date().toISOString(),
}

// Mock projects data
export const mockProjects = [
  {
    id: "1",
    title: "Company Website Redesign",
    description: "A complete redesign of our corporate website with modern UI/UX",
    status: "in_progress",
    customer_id: "mock-user-id",
    pricing_tier: "standard",
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    progress_percentage: 65,
    total_tasks: 12,
    completed_tasks: 8,
    technical_requirements: "React, Next.js, Tailwind CSS",
    required_skills: "Frontend development, UI/UX design",
    deliverables: "Website, source code, documentation",
    budget: 5000,
    payment_type: "fixed",
    start_date: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    duration_days: 60,
    priority: "high",
    visibility: "public",
  },
  {
    id: "2",
    title: "E-commerce Platform",
    description: "Online store with product catalog and payment processing",
    status: "pending",
    customer_id: "mock-user-id",
    pricing_tier: "premium",
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    progress_percentage: 0,
    total_tasks: 20,
    completed_tasks: 0,
    technical_requirements: "Next.js, Stripe, PostgreSQL",
    required_skills: "Full-stack development, payment integration",
    deliverables: "E-commerce platform, admin dashboard",
    budget: 12000,
    payment_type: "hourly",
    start_date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    duration_days: 90,
    priority: "medium",
    visibility: "private",
  },
  {
    id: "3",
    title: "Blog Platform",
    description: "Content management system for publishing articles",
    status: "completed",
    customer_id: "mock-user-id",
    pricing_tier: "basic",
    created_at: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    progress_percentage: 100,
    total_tasks: 8,
    completed_tasks: 8,
    technical_requirements: "WordPress, custom theme",
    required_skills: "WordPress development, PHP",
    deliverables: "Blog platform, documentation",
    budget: 2500,
    payment_type: "fixed",
    start_date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    duration_days: 30,
    priority: "low",
    visibility: "public",
  },
]

// Mock tasks data
export const mockTasks = [
  {
    id: "1",
    project_id: "1",
    title: "Design Homepage Mockup",
    description: "Create a mockup for the new homepage design",
    status: "completed",
    task_group: "design",
    assigned_to: "mock-user-id",
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    projects: {
      id: "1",
      title: "Company Website Redesign",
    },
    assigned_to_profile: {
      id: "mock-user-id",
      first_name: "John",
      last_name: "Doe",
      profile_image: null,
    },
  },
  {
    id: "2",
    project_id: "1",
    title: "Implement Responsive Layout",
    description: "Make the website responsive for all device sizes",
    status: "in_progress",
    task_group: "development",
    assigned_to: "mock-user-id",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    projects: {
      id: "1",
      title: "Company Website Redesign",
    },
    assigned_to_profile: {
      id: "mock-user-id",
      first_name: "John",
      last_name: "Doe",
      profile_image: null,
    },
  },
  {
    id: "3",
    project_id: "2",
    title: "Set Up Payment Gateway",
    description: "Integrate Stripe payment processing",
    status: "pending",
    task_group: "development",
    assigned_to: "mock-user-id",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    projects: {
      id: "2",
      title: "E-commerce Platform",
    },
    assigned_to_profile: {
      id: "mock-user-id",
      first_name: "John",
      last_name: "Doe",
      profile_image: null,
    },
  },
]

